blog/urls.py
from django.urls import path
from .views import *

app_name = 'blog'

urlpatterns = [
    path('<int:year>/<int:month>/<int:day>/<str:slug>', view_post, name = 'view_post'),
    path('posts', post_list, name = 'post_list'),
]

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/',views.about, name='about'),
    
] + [path(page + '/',views.coming_soon, name=page) for page in ['applications']]

georesume/urls.py
from django.urls import path
from . import views

app_name = 'georesume'

urlpatterns = [
    path('', views.resume_view, name='resume'),
    path('api/jobs/', views.job_data_json, name='job_data'),
    path('job_geojson/', views.job_geojson, name='job_geojson'),
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('resume/', include('georesume.urls')),
    path('', include('core.urls')),
    path('portfoliogallery/', include('portfoliogallery.urls')),
    path('blog/', include('blog.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfoliogallery/urls.py
from django.urls import path
from . import views

app_name = 'portfoliogallery'

urlpatterns = [
    path('', views.ProjectListView.as_view(), name='project_list'),
    path('project/<slug:slug>/', views.ProjectDetailView.as_view(), name='project_detail'),
    path('category/<slug:slug>/', views.CategoryProjectsView.as_view(), name='category_projects'),
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render

def home(request):
    return render(request, 'core/home.html')

def about(request):
    return render(request, 'core/about.html')

def coming_soon(request):
    return render(request, 'core/coming_soon.html')

templates/core/about.html
{% extends 'core/base.html' %}
{% block extra_css %}
{% load static %}
<style>
body {
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    line-height: 1.6;
    color: #333;
    background-color: #9cb399;
    background-image: url('../../static/contour2.svg');
    background-repeat: no-repeat;
    background-size: 400%;
    background-position: 65% 15%;
}
.container-big {
    vertical-align: middle;
    height:100vh - 65px;
    width:100vw;
    justify-content: center;
    flex-direction: column;
}

.row {
    background-color: #e9ecef9f;
    border-radius: 8px;
    height:70vh;
    width: 75vw;
}
</style>{% endblock %}
{% block title %}About This Website{% endblock %}

{% block content %}
<div class="container-big"> 
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <p class="lead">This website was designed from the ground up to practice full stack web development tasks.</p>
            <div class="mt-4">
                <h3>Tech Stack</h3>
                <ul>
                    <li>Web Frameworks
                        <ul>
                            <li>Front End
                                <ul>
                                    <li>html (Django Template Language)</li>
                                    <li>css</li>
                                    <li>Bootstrap for buttons and layout</li>
                                    <li>d3.js for map visualizations</li>
                                </ul>
                            </li>
                            <li>Back End
                                <ul> 
                                    <li>Python</li>
                                    <li>Django</li>
                                    <li>sqlite</li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                    <li>Server
                        <ul>
                            <li>Hosted on a Digital Ocean VPS</li>
                            <li>Gunicorn WSGI Server</li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/core/base.html
<!-- templates/base.html -->
{% load static %}
<style>
    a {
        outline-color: transparent;
    }
    a:link { 
        color: #2e2e2e
    }
    body {
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        line-height: 1.6;
        color: #333;
        background-color: #9cb399;
        background-image: url("{% static 'core/contour2.svg'%}");
        background-repeat: no-repeat;
        background-size: 400%;
        background-position: 65% 15%;
        padding-top: 65px;
    }
</style>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    {% block og %}{% endblock %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    
    <link rel="stylesheet" href="{% static 'core/css/main.css' %}">
    {% block extra_css %}{% endblock %}
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
            <a class="navbar-brand" href="{% url 'core:home' %}">Home</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'georesume:resume' %}">Resume</a>
                    </li>
                    <li class='nav-item'>
                        <a class="nav-link" href="{% url 'portfoliogallery:project_list' %}">Portfolio</a>
                    </li>
                    <li class='nav-item'>
                        <a class="nav-link" href="{% url 'blog:post_list' %}">Blog</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <main class="container mt-4">
        {% block content %}{% endblock %}
    </main>

    <footer class="mt-5 py-3 text-center text-muted">
        <div class="container">
            <p>&copy; {% now "Y" %} tim clark. All rights reserved.</p>
        </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://d3js.org/d3.v7.min.js"></script>
    <script src="https://d3js.org/d3-geo.v2.min.js"></script>
    <script src="https://d3js.org/d3-drag.v2.min.js"></script>
    <script src="https://d3js.org/d3-zoom.v2.min.js"></script>
    <script src="https://d3js.org/topojson.v3.min.js"></script>
    {% block extra_js %}{% endblock %}
</body>
</html>

templates/core/coming_soon.html
{% extends 'core/base.html' %}
{% block extra_css %}
{% load static %}
<style>
body {
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    line-height: 1.6;
    color: #333;
    background-color: #9cb399;
    background-image: url('../../static/contour2.svg');
    background-repeat: no-repeat;
    background-size: 400%;
    background-position: 65% 15%;
}
</style>{% endblock %}
{% block title %}Coming Soon{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-8 offset-md-2">
        <h1>Coming Soon!</h1>
    </div>
</div>
{% endblock %}

templates/core/home.html
{% extends 'core/base.html' %}

{% block extra_css %}
<style>
.big-container {
    display: flex;
    background-color: #e9ecef9f;
    border-radius: 8px;
    height:70vh;
    vertical-align: middle;
    width: 75vw;
    justify-content: center;
    margin: 2rem;
    flex-direction: column;
}
.small-container {
    display: flex;
    border-radius: 4px;
    height:fit-content;
    justify-content: center;
    vertical-align: middle;
    margin: 1rem;

}
.child {
    flex: auto;
    gap: 1rem;
}
</style>
{% endblock %}
{% block title %}My Portfolio - Home{% endblock %}

{% block content %}
<center>
    <div class="big-container">
        <div class="small-container">
            <h1 class="child">Welcome to my space</h1>
        </div>
        <div class="small-container">
            <p class="lead">
                I'm a data scientist with a focus on geography. This is a space to collect projects, portfolios, and host my resume. 
                This website is a practice project branching out into web development. To find out about how the site was built, <a href="{% url 'core:about' %}">click here.</a>
            </p>
        </div>
            <div class="small-container">
                <span class="child">
                    <a href="{% url 'georesume:resume' %}" class="btn btn-outline-dark btn-lg">Resume</a>
                </span>
                <span class="child">
                    <a href="{% url 'blog:post_list' %}" class="btn btn-outline-dark btn-lg">Blog</a>
                </span>
            </div>
        </div>
    </div>
</center>
{% endblock %}